{
 "title": "cStor Pool",
 "tags": [
  "OpenEBS",
  "cStor"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cstor_pool",
    "query": "label_values(openebs_pool_status, cstor_pool)"
   },
   {
    "name": "spc",
    "query": "label_values(openebs_pool_status{cstor_pool=\"$cstor_pool\"}, storage_pool_claim)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pool information",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<html>\n<head>\n\n<script>\nwindow.onload = load('$cstor_pool', '$spc');\n\nfunction getCell(name, value) {\n  return \"<div class=\\\"col-lg\\\"><center><p>\"+name+\"</p><p>\"+value+\"</p></center></div>\";\n}\n\nfunction load(poolNameStr, spcStr) {\nvar poolNameStr = poolNameStr.replace( /[{}]/g, '' );\nvar spcStr = spcStr.replace( /[{}]/g, '' );\n//var kindStr = kindStr.replace( /[{}]/g, '' );\n// var pools = poolsStr.replace( /[{}]/g, '' );\n// var rc = replicaCount.replace( /[{}]/g, '' );\n// if(!rc) {\n//   rc = \"none\";\n// }\n// var uptimes = uptime.replace( /[{}]/g, '' );\n// if(uptimes) {\n// var seconds = parseInt(uptimes, 10);\n\n// var days = Math.floor(seconds / (3600*24));\n// seconds  -= days*3600*24;\n// var hrs   = Math.floor(seconds / 3600);\n// seconds  -= hrs*3600;\n// var mnts = Math.floor(seconds / 60);\n// seconds  -= mnts*60;\n// uptimes = days+\" days, \"+hrs+\" Hrs, \"+mnts+\" Mins, \"+seconds+\" Secs\";\n// }\n// else {\n//   uptimes = \"No Data\";\n// }\n\n\n\nz=\"\";\nz+=getCell(\"Pool Name\", poolNameStr);\n//z+=getCell(\"Name\", volName);\nz+=getCell(\"CStorPoolCluster\", spcStr);\n//z+=getCell(\"No. of Replicas\", rc);\n//z+=getCell(\"\",\"\")\n\ndocument.getElementById(\"volume-info\").innerHTML = z;\n}\n</script>\n</head>\n\n<body>\n\n<div class=\"container\"><div id=\"volume-info\" class=\"row\"></div></div>\n\n\n</body>\n\n\n</html>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "cStor Pool Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "openebs_pool_status{cstor_pool=\"$cstor_pool\"}",
     "legendFormat": "{{cstor_pool}}"
    }
   ]
  },
  {
   "title": "cStor Pool Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "sum(openebs_pool_size{cstor_pool=\"$cstor_pool\"})/(1024*1024*1024)",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "Used Pool Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "(openebs_used_pool_capacity{cstor_pool=\"$cstor_pool\"})/(1024*1024*1024)",
     "legendFormat": "{{cstor_pool}}"
    }
   ]
  },
  {
   "title": "Pool Free Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "(openebs_free_pool_capacity{cstor_pool=\"$cstor_pool\"})/(1024*1024*1024)",
     "legendFormat": "{{cstor_pool}}"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(openebs_total_read_count{cstor_pool=\"$cstor_pool\"})",
     "legendFormat": "read iops"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(openebs_total_write_count{cstor_pool=\"$cstor_pool\"})",
     "legendFormat": "wrie_iops"
    }
   ]
  }
 ]
}