kind: Kustomization
resources: 
- ../../../../base/kargo-project-dev
- sealed-secret.yaml

patches:
- target:
    group: kargo.akuity.io
    version: v1alpha1
    kind: Stage
  patch: |-
    - op: add
      path: /spec/promotionMechanisms/argoCDAppUpdates/0/appName
      value: metallb
    - op: add
      path: /spec/promotionMechanisms/gitRepoUpdates/0/helm
      value:
        charts:
        - chartPath: k8s/helm/metallb-system/metallb
          name: metallb
          registryURL: https://metallb.github.io/metallb
- target:
    group: kargo.akuity.io
    version: v1alpha1
    kind: Warehouse
  patch: |-
    - op: add
      path: /spec/subscriptions
      value:
      - chart:
          name: metallb
          registryURL: "https://metallb.github.io/metallb"
          semverConstraint: ^0.13.12 # most-recent stable 0.x.x version (but less than 1.x.x - I think?)
