kind: Kustomization
resources: 
- ../../../../base/kargo-project-dev
- sealed-secret.yaml

patches:
- target:
    group: kargo.akuity.io
    version: v1alpha1
    kind: Stage
  patch: |-
    - op: add
      path: /spec/promotionMechanisms/argoCDAppUpdates/0/appName
      value: sealed-secrets-controller
    - op: add
      path: /spec/promotionMechanisms/gitRepoUpdates/0/helm
      value:
        charts:
        - chartPath: k8s/helm/kube-system/sealed-secrets-controller
          name: sealed-secrets
          registryURL: https://bitnami-labs.github.io/sealed-secrets
- target:
    group: kargo.akuity.io
    version: v1alpha1
    kind: Warehouse
  patch: |-
    - op: add
      path: /spec/subscriptions
      value:
      - chart:
          name: sealed-secrets
          registryURL: "https://bitnami-labs.github.io/sealed-secrets"
          semverConstraint: ^2.13.3 # most-recent stable 2.x.x version (but less than 3.x.x) 
