apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
spec:
  subscriptions:
    upstreamStages: 
    - name: dev
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/zbialik/gitops.git
      pullRequest: 
        github: {}
      readBranch: homelab
      writeBranch: homelab
