apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cadvisor
  labels:
    app.kubernetes.io/name: cadvisor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cadvisor
  attachMetadata:
    node: true
  endpoints:
    - port: metrics
      scheme: http
      scrapeTimeout: 10s
