apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  labels:
    app.kubernetes.io/name: cadvisor
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: cadvisor
