apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-datasources
  namespace: {{ .Release.Namespace }}
  labels:
    {{ .Values.grafana.sidecar.datasources.label }}: ""
data:
  datasources.yaml: |-
{{ .Files.Get "datasources.yaml" | indent 4}}
