kind: Kustomization
resources: 
- ../base
- sealed-secret.yaml

patches:
- target:
    group: kargo.akuity.io
    version: v1alpha1
    kind: Stage
  patch: |-
    - op: add
      path: /spec/promotionMechanisms/argoCDAppUpdates/0/appName
      value: longhorn
    - op: add
      path: /spec/promotionMechanisms/gitRepoUpdates/0/helm
      value:
        charts:
        - chartPath: k8s/helm/longhorn-system/longhorn
          name: longhorn
          registryURL: https://charts.longhorn.io
- target:
    group: kargo.akuity.io
    version: v1alpha1
    kind: Warehouse
  patch: |-
    - op: add
      path: /spec/subscriptions
      value:
      - chart:
          name: longhorn
          registryURL: "https://charts.longhorn.io"
          semverConstraint: ^1.5.3 # most-recent stable 1.x.x version (but less than 2.x.x) 
