kind: Kustomization
resources: 
- ../base
- sealed-secret.yaml

patches:
- target:
    group: kargo.akuity.io
    version: v1alpha1
    kind: Stage
  patch: |-
    - op: add
      path: /spec/promotionMechanisms/argoCDAppUpdates/0/appName
      value: ingress-nginx
    - op: add
      path: /spec/promotionMechanisms/gitRepoUpdates/0/helm
      value:
        charts:
        - chartPath: k8s/helm/ingress-nginx/ingress-nginx
          name: ingress-nginx
          registryURL: https://kubernetes.github.io/ingress-nginx
- target:
    group: kargo.akuity.io
    version: v1alpha1
    kind: Warehouse
  patch: |-
    - op: add
      path: /spec/subscriptions
      value:
      - chart:
          name: ingress-nginx
          registryURL: https://kubernetes.github.io/ingress-nginx
          semverConstraint: ^4.8.0 # most-recent stable 4.x.x version (but less than 5.0.0) 
