apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: homelab-local
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.178/32 # set to worker node IPs
  - 192.168.0.196/32 # set to worker node IPs
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: homelab-local
  namespace: metallb-system
spec:
  ipAddressPools:
  - homelab-local
