apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: homelab-local
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.240-192.168.1.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: homelab-local
  namespace: metallb-system
spec:
  ipAddressPools:
  - homelab-local
