apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: homelab-local
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.100-192.168.1.249 # should not conflict with other IPs (nodes, pods, etc.)
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: homelab-local
  namespace: metallb-system
spec:
  ipAddressPools:
  - homelab-local
