---
# Source: cert-manager-webhook-duckdns/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-webhook-duckdns
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-duckdns
    chart: cert-manager-webhook-duckdns-v1.2.3
    release: cert-manager-webhook-duckdns
    heritage: Helm
---
# Source: cert-manager-webhook-duckdns/templates/rbac.yaml
# Grant cert-manager permission to validate using our apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-webhook-duckdns:domain-solver
  labels:
    app: cert-manager-webhook-duckdns
    chart: cert-manager-webhook-duckdns-v1.2.3
    release: cert-manager-webhook-duckdns
    heritage: Helm
rules:
  - apiGroups:
      - zb17.duckdns.org
    resources:
      - '*'
    verbs:
      - 'create'
# - apiGroups:
#     - "flowcontrol.apiserver.k8s.io"
#   resources:
#     - 'prioritylevelconfigurations'
#     - 'flowschemas'
#   verbs:
#     - 'list'
#     - 'watch'
---
# Source: cert-manager-webhook-duckdns/templates/rbac.yaml
# apiserver gets the auth-delegator role to delegate auth decisions to
# the core apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook-duckdns:auth-delegator
  labels:
    app: cert-manager-webhook-duckdns
    chart: cert-manager-webhook-duckdns-v1.2.3
    release: cert-manager-webhook-duckdns
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-webhook-duckdns
    namespace: "cert-manager"
---
# Source: cert-manager-webhook-duckdns/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook-duckdns:domain-solver
  labels:
    app: cert-manager-webhook-duckdns
    chart: cert-manager-webhook-duckdns-v1.2.3
    release: cert-manager-webhook-duckdns
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-webhook-duckdns:domain-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager
    namespace: "cert-manager"
---
# Source: cert-manager-webhook-duckdns/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-webhook-duckdns:secret-reader
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-duckdns
    chart: cert-manager-webhook-duckdns-v1.2.3
    release: cert-manager-webhook-duckdns
    heritage: Helm
rules:
- apiGroups: 
    - ""
  resources: 
    - "secrets"
  resourceNames: 
    - "duckdns-token"
  verbs: 
    - "get"
    - "watch"
---
# Source: cert-manager-webhook-duckdns/templates/rbac.yaml
# Grant the webhook permission to read the ConfigMap containing the Kubernetes
# apiserver's requestheader-ca-certificate.
# This ConfigMap is automatically created by the Kubernetes apiserver.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-webhook-duckdns:webhook-authentication-reader
  namespace: kube-system
  labels:
    app: cert-manager-webhook-duckdns
    chart: cert-manager-webhook-duckdns-v1.2.3
    release: cert-manager-webhook-duckdns
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-webhook-duckdns
    namespace: "cert-manager"
---
# Source: cert-manager-webhook-duckdns/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-webhook-duckdns:secret-reader
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-duckdns
    chart: cert-manager-webhook-duckdns-v1.2.3
    release: cert-manager-webhook-duckdns
    heritage: Helm
roleRef:
  kind: Role
  name: cert-manager-webhook-duckdns:secret-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
 - apiGroup: ""
   kind: ServiceAccount
   name: cert-manager-webhook-duckdns
   namespace: "cert-manager"
---
# Source: cert-manager-webhook-duckdns/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cert-manager-webhook-duckdns
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-duckdns
    chart: cert-manager-webhook-duckdns-v1.2.3
    release: cert-manager-webhook-duckdns
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: cert-manager-webhook-duckdns
    release: cert-manager-webhook-duckdns
---
# Source: cert-manager-webhook-duckdns/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-webhook-duckdns
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-duckdns
    chart: cert-manager-webhook-duckdns-v1.2.3
    release: cert-manager-webhook-duckdns
    heritage: Helm
spec:
  replicas: 
  selector:
    matchLabels:
      app: cert-manager-webhook-duckdns
      release: cert-manager-webhook-duckdns
  template:
    metadata:
      labels:
        app: cert-manager-webhook-duckdns
        release: cert-manager-webhook-duckdns
    spec:
      serviceAccountName: cert-manager-webhook-duckdns
      containers:
        - name: cert-manager-webhook-duckdns
          image: "ebrianne/cert-manager-webhook-duckdns:v1.2.3"
          imagePullPolicy: IfNotPresent
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
            - --v=2
          env:
            - name: GROUP_NAME
              value: "zb17.duckdns.org"
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          volumeMounts:
            - name: certs
              mountPath: /tls
              readOnly: true
          resources:
                  {}
      volumes:
        - name: certs
          secret:
            secretName: cert-manager-webhook-duckdns-webhook-tls
---
# Source: cert-manager-webhook-duckdns/templates/apiservice.yaml
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.zb17.duckdns.org
  labels:
    app: cert-manager-webhook-duckdns
    chart: cert-manager-webhook-duckdns-v1.2.3
    release: cert-manager-webhook-duckdns
    heritage: Helm
  annotations:
    cert-manager.io/inject-ca-from: "cert-manager/cert-manager-webhook-duckdns-webhook-tls"
spec:
  group: zb17.duckdns.org
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: cert-manager-webhook-duckdns
    namespace: cert-manager
  version: v1alpha1
---
# Source: cert-manager-webhook-duckdns/templates/pki.yaml
# Generate a CA Certificate used to sign certificates for the webhook
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-webhook-duckdns-ca
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-duckdns
    chart: cert-manager-webhook-duckdns-v1.2.3
    release: cert-manager-webhook-duckdns
    heritage: Helm
spec:
  secretName: cert-manager-webhook-duckdns-ca
  duration: 43800h0m0s # 5y
  issuerRef:
    name: cert-manager-webhook-duckdns-selfsign
  commonName: "ca.cert-manager-webhook-duckdns.cert-manager"
  isCA: true
---
# Source: cert-manager-webhook-duckdns/templates/pki.yaml
# Finally, generate a serving certificate for the webhook to use
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-webhook-duckdns-webhook-tls
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-duckdns
    chart: cert-manager-webhook-duckdns-v1.2.3
    release: cert-manager-webhook-duckdns
    heritage: Helm
spec:
  secretName: cert-manager-webhook-duckdns-webhook-tls
  duration: 8760h0m0s # 1y
  issuerRef:
    name: cert-manager-webhook-duckdns-ca
  dnsNames:
  - cert-manager-webhook-duckdns
  - cert-manager-webhook-duckdns.cert-manager
  - cert-manager-webhook-duckdns.cert-manager.svc
---
# Source: cert-manager-webhook-duckdns/templates/production.cluster-issuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-manager-webhook-duckdns-production
  labels:
    app: cert-manager-webhook-duckdns
    chart: cert-manager-webhook-duckdns-v1.2.3
    release: cert-manager-webhook-duckdns
    heritage: Helm
spec:
  acme:
    email: zachary.e.bialik@gmail.com
    preferredChain: "ISRG Root X1"
    privateKeySecretRef:
      name: cert-manager-webhook-duckdns-production
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        webhook:
          config:
            apiTokenSecretRef:
              key: token
              name: duckdns-token
          groupName: zb17.duckdns.org
          solverName: duckdns
---
# Source: cert-manager-webhook-duckdns/templates/pki.yaml
# Create a selfsigned Issuer, in order to create a root CA certificate for
# signing webhook serving certificates
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-manager-webhook-duckdns-selfsign
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-duckdns
    chart: cert-manager-webhook-duckdns-v1.2.3
    release: cert-manager-webhook-duckdns
    heritage: Helm
spec:
  selfSigned: {}
---
# Source: cert-manager-webhook-duckdns/templates/pki.yaml
# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-manager-webhook-duckdns-ca
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-duckdns
    chart: cert-manager-webhook-duckdns-v1.2.3
    release: cert-manager-webhook-duckdns
    heritage: Helm
spec:
  ca:
    secretName: cert-manager-webhook-duckdns-ca
