---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: duckdns-token
  namespace: cert-manager
spec:
  encryptedData:
    token: AgCbljnuD1IoprWrwAFcQDAgTkEariw+oAUvAk3mUH4aB24irQiXdB1pPjz7vGuX7S4C+vMftQ3RiIB60Rlas1ubuG67MhOIuuEhV4bhAWrKvW9G7SVuyhrz1avyfpFdtiqC+p9ug2jH0a6hWgCe7Cqnisy69qBmD2S5yn/XwWpCJ2gNY+3mSeGkJU6SK8iy6gbRkx1DqsQ2gyPp51KsvqNCh0VFnmwUniBAcgx+G3EOK0Ujr/ZHpp8+El3OlHO2sKHMfh9oJiGsrds6pExfHB2BGPglb4z2H8SzLMpsq6xAAUmSk/3N7IvUnGcJkLwxFngx02OTUIMq/VBG0R779wt738aGcPvKUrH5o0JZJxUx5TlAH3fK/kTBz6yVwPoFmCvT9d57f4QRgR4hyLxOZ+bcLGkY9BrtFGMlIEWj3MXjPKw2KUfYMZ+AyWy2MbZVNVmNi95of01+CIA9hzAABpN/KgE0RD1siXP8O6jQqiFXnlicb6QeyCNmRHvgFnjPDpx3+I1Z94E1xxaiCoJj+4e1EbNXWa/7S4SNv/ZLazbGFHHE0hU3SVJtQQv6Z+ap0hfbYmDAvRsoe3ozNXLzqqPNv6lgXsXgtN8XcxKdI1z3NuCqj0pzNUa5qZpF0JD3QwoOf5XM4ZE8VT3kZx0qHMzSJ85GOMjGBh/F3gLAbWAnL4ugCR6K31uh4KzsaxUOZ6RC2205GZ/wHITi0Ug7cUvrLVoNG0T6w8uL/qQWdn2Zn1y5PdQ=
  template:
    metadata:
      creationTimestamp: null
      name: duckdns-token
      namespace: cert-manager
