configs:
  repositories:
    zbialik-homelab-repo:
      url: https://github.com/zbialik/homelab.git
      name: zbialik-homelab
      type: git
  secret:
    argocdServerAdminPassword: $2a$10$xItx1biJu5Qql.ANf/3Cju/mxYE04WUG5e3I/MoRpxbVSdoDgLN/W

server:
  extraArgs:
    - "--insecure"
