apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: ingress-nginx-dev
spec:
  subscriptions:
    warehouse: ingress-nginx
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/zbialik/homelab.git
      writeBranch: main
      helm:
        charts:
        - chartPath: k8s/helm/ingress-nginx/ingress-nginx
          name: ingress-nginx
          registryURL: https://kubernetes.github.io/ingress-nginx
    argoCDAppUpdates:
    - appName: ingress-nginx
      appNamespace: argocd
