apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zbialik-selfsigned-ca
  namespace: cert-manager
spec:
  isCA: true
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - "Zach Bialik"
  secretName: zbialik-root-cert
  dnsNames:
    - zbialik.com
  ipAddresses:
    - 192.168.0.181
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
