apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-selfsigned-ca
  namespace: cert-manager-homelab
spec:
  isCA: true
  commonName: homelab-selfsigned-ca
  secretName: homelab-root-cert
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
