apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
spec:
  subscriptions:
    warehouse: dev
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/zbialik/homelab.git
      readBranch: main
      writeBranch: main
      # helm:
      #   charts:
      #   - chartPath: k8s/helm/test/placeholder
      #     name: placeholder
      #     registryURL: https://zbialik.github.io/helm-charts
    argoCDAppUpdates:
    - appName: placeholder
      appNamespace: argocd
