apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: node-exporter-dev
spec:
  subscriptions:
    warehouse: node-exporter
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/zbialik/homelab.git
      writeBranch: main
      helm:
        charts:
        - chartPath: k8s/helm/monitoring/node-exporter
          name: prometheus-node-exporter
          registryURL: https://prometheus-community.github.io/helm-charts
    argoCDAppUpdates:
    - appName: node-exporter
      appNamespace: argocd
