apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: main
spec:
  version: v2.48.0
  externalLabels:
    cluster: homelab
    prom_shard: "$(SHARD)"
  podMetadata:
    labels:
      prometheus: main
      app.zb/name: prometheus
  securityContext:
    fsGroup: 65534
    runAsGroup: 65534
    runAsUser: 65534
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 50Gi
        storageClassName: longhorn
  replicas: 1
  shards: 1
  resources:
    limits:
      cpu: 300m
      memory: 1Gi
    requests:
      cpu: 300m
      memory: 1Gi
  enableAdminAPI: false
