apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/zbialik/homelab.git
      revision: proto_kargo
      directories:
      - path: k8s/*/*/*/kargo
  template:
    metadata:
      name: 'kargo-{{path[3]}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
        syncOptions:
        - Replace=true
      source:
        repoURL: https://github.com/zbialik/homelab.git
        targetRevision: proto_kargo
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'kargo-homelab'
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/zbialik/homelab.git
      revision: proto_kargo
      directories:
      - path: k8s/helm/*/*
  template:
    metadata:
      name: '{{path[3]}}'
      annotations:
        kargo.akuity.io/authorized-stage: "kargo-homelab:{{path[3]}}-dev"
    spec:
      project: default
      syncPolicy:
        syncOptions:
        - Replace=true
      source:
        repoURL: https://github.com/zbialik/homelab.git
        targetRevision: proto_kargo
        path: '{{path}}'
        helm:
          valueFiles:
          - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[2]}}'
