apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-demo
  namespace: kargo-demo
spec:
  subscriptions:
  - chart:
      name: prometheus-node-exporter
      registryURL: https://prometheus-community.github.io/helm-charts
      semverConstraint: ^4.23.0
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-demo
spec:
  subscriptions:
    warehouse: kargo-demo
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/zbialik/homelab.git
      writeBranch: main
      helm:
        charts:
        - chartPath: k8s/helm/monitoring/node-exporter
          name: prometheus-node-exporter
          registryURL: https://prometheus-community.github.io/helm-charts
    argoCDAppUpdates:
    - appName: node-exporter
      appNamespace: argocd
# ---
# apiVersion: kargo.akuity.io/v1alpha1
# kind: Stage
# metadata:
#   name: uat
#   namespace: kargo-demo
# spec:
#   subscriptions:
#     upstreamStages:
#     - name: test
#   promotionMechanisms:
#     gitRepoUpdates:
#     - repoURL: ${GITOPS_REPO_URL}
#       writeBranch: stage/uat
#       kustomize:
#         images:
#         - image: nginx
#           path: stages/uat
#     argoCDAppUpdates:
#     - appName: kargo-demo-uat
#       appNamespace: argocd
# ---
# apiVersion: kargo.akuity.io/v1alpha1
# kind: Stage
# metadata:
#   name: prod
#   namespace: kargo-demo
# spec:
#   subscriptions:
#     upstreamStages:
#     - name: uat
#   promotionMechanisms:
#     gitRepoUpdates:
#     - repoURL: ${GITOPS_REPO_URL}
#       writeBranch: stage/prod
#       kustomize:
#         images:
#         - image: nginx
#           path: stages/prod
#     argoCDAppUpdates:
#     - appName: kargo-demo-prod
#       appNamespace: argocd
