---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: duckdns-token
  namespace: cert-manager
spec:
  encryptedData:
    token: AgB+d5nfCjpHo56VTT6acVm/oo8oMCQIuIO9rZxFXXXGPhdGVMObynXOCpasPIoE9Os1T3GOlC9LR6p97AacsFkJFVD+5fZ/tGtLOOriCLQvZyfyLuJc67QrcGv6d9OY2Al9wBSo2Ch7GkAVULhDBwDRndZK1zIQAzD0L7SUmEoeCLHtJAbRXexus8FSJfeqQpIoRxPiLPrNOUhyHcWxvhFw1/G4t7Ts5EmM+HoYcIMHcXcmbClSg9ydNhENBsk9wHPfTIZ8euVtAV+jTH/qu5PdrWVaEI0Qf2BOtP/9BaTavYSXwkc9B4MT74sD96IUbEBpq6nVBFGp1xV91t6E1npiMo4/NUwFSBg5PMlOcF7lKqixOvjDy6YiJj/W9hMZv4sD1/u6ttbO/tMyOuhCBRVSH7124bQDCuVi3WyK5fm11mX2mNb4hahljPOTJw0Yggr9QHddaSKsFCLQBLJWrYudrSK13qd2Q4bdWS7Lov+Bd5ZZg/Ugb0qGQhi0dOu1X/Vlxy4/m19BWQbAyix3y87sVlo2T46/Pc6WU3Q/6d3a5kfl2CxNfaQBr9zQleu2gWBpOFZl8emddvkIzYbiin6mHj9gCAaVOE8AsvZ6C+i+lBsRYvzHD+RFEHtvEU6ZJBEGKb8cp/JQVpmB+yz0XANE1rFkGEma5xcMdGwRuwUDPRhm8a9tVx+T6Osmv5bv0gV5SXnpXbWXD4R7VgOQhYo5+bHyhmwvQREvRj29xtVAVKuQWBI=
  template:
    metadata:
      creationTimestamp: null
      name: duckdns-token
      namespace: cert-manager
