---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: duckdns-token
  namespace: cert-manager
spec:
  encryptedData:
    token: AgCCiwuo6drKdm4ML9q63f6Fmg4GUvd5CXL7vSUgppd1Y7j4LICz/wmTZdakxi0nFaZz/nkLp2vZFYJlU+f1ESfo/K0dJ2Yn3Dsy2KV6go1u+leibN9lOXHPFEkXSoX2wGLpJl32hNjZts3JnZwd2IG8LM1wm9OP6TXeLJZQ6yNfEgcFI+Q9P/MIkokWwIG3KsvLVzHZ0giyn1oZtYJGOt/L9kGyHeBY3uLc2Cbh38uEq2IrL74itowGmhafM9x19uxtyMu+uJz/hRrp9C1jYRaDKJXeYqeNoElRAEDdFzXVp39ks9cTvBgzIPNOkcUVsZOkPpndDRkRj1Zv4hZRvB7+8QpHQyR8GP4wH3ogH/2nlZwU1psSrJIsBDZQssxjeuNmgiDV+CthSbLnOUbwxcIZaiUjYVuPgYxZ/IeK67U7+4HMWw6T14RVmz6PK0HFFNAuL25slGfMPVinLLjUGGQhtaIcQdLhVlt4M4PuFxen/RP7vCPYC+A/Q4rmDhIxsR9Vhl25xR16p1EdapdeqXsecJNzWrR6lRWUoiVzuB+fitg+bwbqTQr6ad6RZgQBucaUwf2ApEQA0sZQCPkeG0jxUWvYYRoCGe5tpL06z+to9nGrUTdE3e1rSvLrV0cKzd3jkMY+Xr9f1p+s/PaLh2ytN/SyX4iMOgiFMKCGfS04xU4Tg6NKdv51bv7yoTBprrl3yJhRVWPxBm2QYDfgg4FSOVoWrL8/IZrk2bZbeZVFBOF3KYE=
  template:
    metadata:
      creationTimestamp: null
      name: duckdns-token
      namespace: cert-manager
