---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: duckdns-token
  namespace: cert-manager
spec:
  encryptedData:
    token: AgAP4IqB0QCuLnfidamD+BaMxKAjHS9UlHOKI8Z02z1ZRpJBFGLFSXuET4qBWhbwi2Rc0Iogly3AR4ZPWRLDGXSmy9ylpWNrRL+kEGBprvP53a79CTEz09e06KVKjtrcbPpNJ0NGYf2vVq1Tgc0lycxCaHsdCiEO78c73DOgdgbPQQc6m6Imi8MueqLZI3JOrm0+Hc+wBemuBYR9DysYyvbHF6H55uxEdSpHROMfBmerLfDatoryry1/rslTFg8B0o3mcdEKfiP85PKf+4uzp6/fykq6tc5DBEmBTJvHiQdFOG0DFaN5U9wINzIty1MK4vunWkwVu8MvDUqgDe8uW/Y8US2vUuDBN9thFWUpIEBCerlq026YlYAkvKuOxvHyuPlxmkXPeNWlDXCvfsAnbLUj/nVTcQsFZi8WEFcRJ+2E1cxUTwXNbSNZp8xCZf7uZUpuXW6ZyQghhG6mOfES8FayoC3JQpkQ7frt1idqztjcyOPHLdIouHsqeo3hnEeJMf4/eC5GwmJZ+YGuzxWNM5Oa39rBrnv5+aZZO5foIKWU9EqPa5h20J3hX5eBxw9ms7IcThiwHCNiev30BeZkHPBWRmSYxNt+UwaeLS+oHggl6+I8SqcQbQJmI54+pz8m5A8vy9NCrVVQtnA0fk4oCU3anPrcNguswa7TwJHYQwxYO1qakolQbIPpxHkCE1sT1Ier4yyndoRN9OD1yrzaeTyC956N7jxqr4KJlBIcTnuNH3gl5uE=
  template:
    metadata:
      creationTimestamp: null
      name: duckdns-token
      namespace: cert-manager
