---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: duckdns-token
  namespace: cert-manager
spec:
  encryptedData:
    token: AgCYy+dqJQc9fevjz3qFaqQuJtmO+w96lEj3PNwkMl+uPA4ubY+e3GintwWsAStD8lWHEQw1Za2T4hPUAOCnnvW7xE+xBwsEytBtcE0zx3cfwc+TZ8PcnATJRzL+jYIYGglQM5hVB7HHpze6FrrDgvuBKbMiTN6PeHHx3xEu9zq4E0lX16v47HlntkoAkOncpWRH2qdxSB3TNQ0ZPtXzPdvoApYjzbYtkzvABcCKbxChh7VsjGbHkSx5Dvx2JsiplmF2g/nDcMlL4wYm5tvRDnWbHocy3HTWuaZvrsFvwjQhz6G20vlGS9C6ST2epNsg7fluDSR0pKCRYAXqyNnTcrrq9W32vp19FbuX2piF2IA0XCSaGf0zx58xXvIi6Z8NKgtYJBTImpnt3pR6FdafXDpmMt3+MPRKiSU7jcXRN2d92GPp7POYeV5+TKsj8rteYB/OPPCRNhEpzkrz6pN4GYpiELq/WBFLZcJYaw9SLH8FOfvsSxsImjJxu5IegHo4sZJ9rbBFze1UKHS2GxWiZUPt52HnsQbd93YymzcIkpTifXL5LENGWwF2BkhUQTLiG16lKWlgpVqRkqyNmdAjKAJTWbu0j3hXCvesV8GFaTvnTvjVTaqQv9kvR1tXfE40Ffw4ilf5twmblHHMHMiKZ9Z4wtbm3EdpE/I52FidcVTj/YZYp6hmjlwQn/9vsYmyW+C8GyaX/zDzNXmDVBNKmWx7PPm8JnK0MTvsU1ZZ5XHbLS6oAac=
  template:
    metadata:
      creationTimestamp: null
      name: duckdns-token
      namespace: cert-manager
