cert-manager:
  installCRDs: true 
  resources:
    limits:
      cpu: 100m
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 32Mi
  webhook:
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 5m
        memory: 16Mi
  cainjector:
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 5m
        memory: 32Mi
