apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: verify-ci-complete
  namespace: kargo-homelab
spec:
  metrics:
  - name: verify-ci
    provider:
      job:
        metadata:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: test
                image: alpine:latest
                command:
                - sleep
                - "300"
              restartPolicy: Never
