apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          image: zengxs/gitlab:16.7.3-ce.0
          ports:
            - containerPort: 443
              name: https
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 1
              memory: 2G
          volumeMounts:
            - name: config
              mountPath: "/etc/gitlab"
            - name: log
              mountPath: "/var/log/gitlab"
            - name: data
              mountPath: "/var/opt/gitlab"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: gitlab-config
        - name: data
          persistentVolumeClaim:
            claimName: gitlab-data
        - name: log
          persistentVolumeClaim:
            claimName: gitlab-log
