apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: main
spec:
  version: v2.48.1
  externalLabels:
    cluster: homelab
    prom_shard: "$(SHARD)"
  nodeSelector:
    nodegroup.zb/persistent-data: 'true'
  podMetadata:
    labels:
      prometheus: main
      app.zb/name: prometheus
  securityContext:
    fsGroup: 65534
    runAsGroup: 65534
    runAsUser: 65534
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 100Gi
  replicas: 1
  shards: 1
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 2Gi
  enableAdminAPI: false
