deploymentStrategy:
  type: Recreate


ingress:
  enabled: true
  ingressClassName: nginx
  # annotations:
  #   cert-manager.io/cluster-issuer: cert-manager-webhook-duckdns-production

  hosts:
    - grafana.zeb17-int.duckdns.org

  tls:
   - hosts:
       - grafana.zeb17-int.duckdns.org
  #  - secretName: grafana-cert
  #    hosts:
  #      - grafana.zeb17-int.duckdns.org


resources:
 limits:
   cpu: 1
   memory: 1Gi
 requests:
   cpu: 250m
   memory: 500Mi

persistence:
  type: pvc
  enabled: true
  # storageClassName: default
  accessModes:
    - ReadWriteOnce
  size: 50Gi

admin:
  ## Name of the secret. Can be templated.
  existingSecret: "grafana-admin"
  userKey: username
  passwordKey: password

sidecar:
  resources:
    limits:
      cpu: 100m
      memory: 250Mi
    requests:
      cpu: 10m
      memory: 100Mi
  dashboards:
    enabled: true
    label: grafana.zb/dashboard
    folderAnnotation: grafana.zb/folder
  datasources:
    enabled: true
    label: grafana.zb/datasource
