ingress-nginx:
  fullnameOverride: ingress-controller
  controller:
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        memory: 90Mi
    service:
      enabled: true
      loadBalancerIP: "192.168.1.100"
    extraArgs:
      default-ssl-certificate: $(POD_NAMESPACE)/wildcard-zeb17-internal

