apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zeb17-internal
spec:
  secretName: wildcard-zeb17-internal
  dnsNames:
  - "*.zeb17-int.duckdns.org"
  issuerRef:
    name: letsencrypt
    group: cert-manager.io
    kind: ClusterIssuer
