kind: Kustomization
resources: 
- ../../../../base/kargo-project-dev
- sealed-secret.yaml

patches:
- target:
    group: kargo.akuity.io
    version: v1alpha1
    kind: Stage
  patch: |-
    - op: add
      path: /spec/promotionMechanisms/argoCDAppUpdates/0/appName
      value: grafana
    - op: add
      path: /spec/promotionMechanisms/gitRepoUpdates/0/helm
      value:
        charts:
        - chartPath: k8s/helm/grafana/grafana
          name: grafana
          registryURL: https://grafana.github.io/helm-charts
- target:
    group: kargo.akuity.io
    version: v1alpha1
    kind: Warehouse
  patch: |-
    - op: add
      path: /spec/subscriptions
      value:
      - chart:
          name: grafana
          registryURL: "https://grafana.github.io/helm-charts"
          semverConstraint: ^7.0.0 # most-recent stable 7.x.x version (but less than 8.x.x) 
