dns01RecursiveNameserversOnly: true
dns01RecursiveNameservers: "8.8.8.8:53,1.1.1.1:53"

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 10m
    memory: 32Mi

prometheus:
  enabled: true
  servicemonitor:
    enabled: false
    prometheusInstance: default
    targetPort: 9402
    path: /metrics
    interval: 60s
    scrapeTimeout: 30s
    labels: {}
    annotations: {}
    honorLabels: false
    endpointAdditionalProperties: {}

webhook:
  resources:
    limits:
      cpu: 100m
      memory: 64Mi
    requests:
      cpu: 5m
      memory: 16Mi

cainjector:
  resources:
    limits:
      cpu: 100m
      memory: 64Mi
    requests:
      cpu: 5m
      memory: 32Mi