controller:
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi
  priorityClassName: "system-cluster-critical"

speaker:
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
    limits:
      cpu: 250m
      memory: 128Mi
  priorityClassName: "system-cluster-critical"
