---
- name: Configure eth0 for raspberry pi to get IP from DHCP
  hosts: all
  become: yes
  tasks:
    - name: Create or modify 99-disable-network-config.cfg to prevent override on reboot
      copy:
        dest: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
        content: |
          network: {config: disabled}
        owner: root
        group: root
        mode: '0644'
    - name: Modify 50-cloud-init.yml for eth0 config
      copy:
        dest: /etc/netplan/50-cloud-init.yaml
        content: |
          network:
              version: 2
              renderer: networkd
              ethernets:
                  eth0:
                      dhcp4: true
              wifis:
                  wlan0:
                      access-points:
                          "Harold's Wifi":
                              password: "redacted"
                      dhcp4: true
                      optional: true
        owner: root
        group: root
        mode: '0644'
    - name: Apply netplan
      command: sudo netplan apply
