kind: Kustomization
namespace: grafana
commonLabels:
  app.kubernetes.io/name: grafana

resources:
- deployment.yaml
- ingress.yaml
- pvc.yaml
- service.yaml

images:
  - name: grafana
    newName: grafana/grafana
    newTag: 10.2.2
  - name: k8s-sidecar
    newName: kiwigrid/k8s-sidecar
    newTag: 1.25.3
