---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    password: AgBEkTuLbpvee/KHAY9Ivh2M3DW+MvXpufR4rY1f1hLQnHXI9EEHmJ0KkSPTt5I+txMnolP8l8rO1O7ACF5vXzPoq4IanuVlGNQ94E73EG/VxlUXvOjD5aU7jm1TXi/QFxEzmQcnDnGxB3me1FTu1O3dKyeHN/M3IXRdSQDCh38uMhaRS2d1wzORgUlb3IGxrEAx38ramvjH3TqLodWu46DJetuZuAMzUQ0KtdS+kfORUr8boZOFDkCmbWHfjUchL6emxnFKZT6Fzy077RwLoFytXgvqK3k6l4HRfC8VBgZitk05lMZZ+RV8ccm/at5WXCCM2erFbkK3eEZQ0VVwyXDd9GQf4wOoW4KHzHbO6BcCpKkmzXNvoY8jU2YFA/3jEq50Ggqu1D66Fi8BH74aANKrJjC0zZFMNUS2NYoQEhambqhP1vuKa8wWr83ojWvyp8/YSkm1um8buh0h4aiivGGwuHkDTZimtZ+OZCn3Y6uvm58dkEx4V4d0GR5QmDKqEfyO3oTH3wPqQwkPdwFDgXBNLK8aj00Lg1rvQ62MHuDYIpbO1XibxEEsNAldLVfzNQWYh9rl1354+dTnb+uCI+HvoJXZk5jPqnezKcnn1NqqaiYjAUfs4mjKBcKFf87SYlyilP3CTHWHvJiAThnNSP/sIM/IEKGFVG34L9XI2WyfrgaxfKJJKYBRjGEWVZmgHLoAHoC2MN8yjNkUEzVbrp7kIkoa6VrHg0osBukmEtUNPc+H8gTJmC3rKlVpfZkBCqkXwWrb4p+9Jt9pfgk=
    username: AgBaU1HjM3JekbKszX1QnGCHd3HlmIFeEckx7PKazL9wGsBr+6Sl9G/+LvgOCIwPEr4WV1S/GEGyMp/M2M+WtunIq/RxLEEK+vYQBHIpqsB0tNEALOCqpCCkoXMfFUELrOIUxLQHBRDg+glBWNBs2hje7r2AI5c7Cf+yroEgm9quI3NbgXQCiOddQX5PRueskRNgKdONt4bs3cSzWYhehyePgWah8MIsssVRt1h9dlTbCwilKhiO8+jRcI0HxR0MKH7bxdBIcRM0Z/BH6SaU0qE7SYNVkmxKDywKCzukJipK+REN971tB654Fa1w0iQVkEa+zkxP7yxzcE9zjPzW66tlGVzZga3d/KwH1Zi3YlrGm45Kpc+f88QjHwmi6/8HZgRB+G8b+o7aryf9mlrLmw9srlhcU1BqrkUT1LZO1peEGj/uhbSVCOIQ1cvs4I5IwKwf6QGKnWRbmzI0CfdqOCD4FdIxKIGXb8ocvMjp7YW5S77y2lagfMrPTp0W5Z7TDJDwc2rFhSKzB6pJQ72kvWkKS5SqZi2exKWqlsddEofSriSIVG+EsiSJ8okiHWj4YrHRu3/u3vciukYkkOvnkLRmW6SlzTwSQa6fCHADshx94MOqOY9iUhPgu/7qGhR3rllqx/M00jkUVwdxu+mi89RcZJHVYq8otrCiDuk3At054nrAxE4JPGqTrGr5lZZSUSUmk7Dx1w==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: grafana
