---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    password: AgCYS8hWa4oQn6fr2/Dy8XfEaWWch7vduG9MLBqBsBCIfUf5k2G+ZmieDJRFg1Seb0mj4W9Z1Xx6B7qJIS6CSoDATYhlQORnuO1wITpYCBspSOeOjw82+LGBk65IENjA/NvVO+B0z+/Sc+aGVT4En2JEwJJgt9OAxyKYJIKpT4rPDs9FOeVgOX8OihNr79Ol4Hv2aG5CoeGrPxWOKbcv1OJEfUXxvjQct3pU8GAR9BdT1J46PMZxbsiDVPF3+XlNL710TbYCrk04MqygtEfTHH+ac2mWxmB//XV7Xx//ieacUqFZiIF797c4YbN512tOsPQRnuoP5bW5WYfJvOtdGZqmUhPUKOyGYVKeXF1qWfFNO5592hPUChPM6JFm3NdqTw3HIMHLLdSO2+DljoGC3foxqifZ1tZPrPgcsQBep8EJGws+unOXYizz8DKIycNaZqrE1/6mkfOakFgC7+LSBPx9bl2I51bVER1OwRZMCXOYYJ4Wr8+HVB1w0mU5je1fWgn1m2EUuyXGXQZBdKKtCqFrQz15zP3dYS5nzOrPn0n7sFYissr5Z02XtK8UMNMvTMwuf7DJRRN3ARnNO1sm0cM7YahCqM5Ink5bAREhxkn8PKu1fqiGD5fC9vI8HPw4J1KgdaCbRdgps0OwWlb2glhTOoHDTFaGpb2O+Keykbeq2EBlKQtyRAhl7Vbfn/KuMFqgCo/p1m1VVMKSMTCYmhG9Tn+aXaNnShA2CyNWm9e2UOxu42CLAUS6rVqULxAEhBG1heyUtk9ND5woWVqw
    username: AgCH3qBYcdvvj+vAz7ieQXcYUDTiE5ZpRCHpxyjg2V6usd4V9rBFXAKGqD1gWK2A3kYdSF5sZ+ovEBod9emM9nK8u47dIoZgLZjg5+6n/iyjzahBADcXPscmLuuIVSbYvhpSSKfwpWXHANhBFhzMEbccU281HOJXFP90uqh1zAcmdOO/p2r4abm14VoYGndcOeGHImC7odNPdiKAVUYSAVY3ALLuh5ZryCAZ1N1s+1w5km2zY8OrUYOC47sqO6ZDirwuNLH0f3VUPJPLRhkcfz6VIRd5kDaJ8NtLtiuSW4eek9KDmOyRtrx/1i82Pir3Mwdbv46hUj37o4o0+vPfmE9byQfDSnLMqrZvXrisIPJh2HfaSd2q+P0JPRnQWkT5vzJQzZZJFZG8m6fAGYi3P++BRdDzSbz3GkPJ9ItIBA/DDgtpiPkVbHBSrFY/LM0seibfANE9f2O5EJYYp1oJlB+QEy2V+S9bI6EewJjFVOCxK3/eMy8mzr0Q5p0KZP+r9Hxzb5iIcb4jv0NilBd8vouYfCpPF4+XsqC/9crW+hZyVJxchlQA2G3Rf1uy/VsU1eYderEobKe10Ltxxd0up61zNZl6/05lyoPsDXVgzI9ms9dtHRztw0rB3cLn51gYFpB40q/8i8U/QoVhcfRI5Aj2iva3C0Hhu9BxoQvgrqKyIjZKZok0hI5XgftAGU/Uka8zMDI+Dg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: grafana
