---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    password: AgDI0woHkFh7aLzHuATO7tuVIAhPoB/LUR+CDl5COqvY3hTWU7Mrtg/ki7dKf2zHusvMC1dgeUE/wOn1PbJISxRpVDLWe+ZP1lKGRGCEdG3XIZyylpL3ixnuK13hdFykqPYZWVLKVT4Yg3rLkfdvO7Rt1AjkfA5SSgaOV2Hf4tc0GoA8Fnf/lRcGH8OwuBeZu+SOxM0L0uHeMkFFwifPRap+xWx+kzUFzcW3m8nw7SJ10LlGXikT3wf9WdTBdY+A9rqnar9z+5n3GENceI3B5igUQfmRe1RvcjX4iDnxj8oTd+1wnOGduy8adRBV3C/VCRnO25V3Bvu09wx6vMgqYq29UbzNeF5UU+r8QcZfGhrXFv75aKY1ySF4P+ghZdf43dYnOuOI0lN4i98UBYyXZ5mbSed6GHNJw9RHPEnlLGP5eKaa6GUxGRrTTfkYxnyV+t6PI51WazQSB0EHgvfEQkTHG4Q7OVC8VDviL++Ez+itfUIEfChp3K1y9eWK11HQIlGWTR+YEW+il0vzBBSaHpWraGmhlrvrELurAMdxpWtd35Ff/7uD0KJ1C+5RQMctl5ghD+rqRqpOrJtEHJQGBWrainGc83fJ4ujKCIM9PxFeO9nvgdz68vxeFij5HQ/jp/dkEdHlI5gIqmLygWHo6tDCdittYlQqe7RFdlvVODP2etmrqAtOjWm3Cv7q8TWTZSA=
    username: AgCg9NI9dGfv3AyCHbyNxqcaGZ9WpggEjHaD6h6hLrvhMsilZlqrOocHhy7saLsq+GQ7JnnQfs8n/jS/3xn0UUaqk46WISZhQePQQ3Lp0AeWz2grNbaUFWdz/wnvSyQbSHIHPZTuMmXgKWSTmWRJI+/lBtSbV008KupyIL+is+opUxQKA6iworwc5880KiRE/ftBWkbbQcddIqT+RHJ7prkJFIQE8a0dSQH9ARX1ICZzPJoBXhcVVH+66pzuWkNAADMVIBRFI1YQJNuAO79fbrqeOgLROJs2p9E8KuwL43Xab5iK2AcjJh7N2V8DtvTuO3Kbb8UQSEln47c6tTdgLeFJ8hQSS4YjW+lRNn+DeSDz659fOoenFliuwgyJckbeBiKoSPF4s5UgXmh1PNmfiBVkfpBB5pmIveGQir2FmkEuLAT6SJeYW+fDF8gCwqCcJGE7/NJpBNPzB8wJl2bg4ajkcfm3/MlDI3m9WoEyXry+4+tmvUD1EbedEzqDxz0Rl7pYrK5OeVcjnD9P9gDDsVdPgagL4tzxZvWrohFw+gXQb0R/Fu53kn//nXxj1zUAu1gvLzkgJNb6nx2sQJMSaGE42/BYh+VtVnGKArntTlmGWtPPnHIPONgKhDDVOIZvQA4QXqKPC+51yErfjm2j0Lr39fpyaxiyscAtvx3hiloiUHA+d2QKaSW2Fk3hr0btEXGQ5Qsrbw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: grafana
