---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin: AgB1iDZssV2b+6+nUW4b+vzvc/93EeMkB1WDSBuTAG2DpkKSgl0zejpcmYHOPXoRcI4g8lhVQk7VJjJvAzB0t5UXV+ZGzWH8tDwEDcuoieCuHitX5oxgzKrvhvIGGLqVloGy2sf0CORYb0js2oNSKfcOdBCRmW+U5b0bwXjwh0v5BIENeg58gO3NdlpAbe594ag9uWXY40lD0SqoT2GGqHEVmK9W8RkhncVr3Oy043AJGUQnPVKwaDLL+74nNlLjnGxwHEXFhosXWYDNh1iup1HdtpyzkJk+4eLRa2aLP23IsFKYHlRfGE80p2n6dHfRwdBmdzBE5iWY8yEGoZkKzivM9baLmUB6/0Z+WhekHucDvWa5ZtcYODaDLf0bKQho4S/IDYfIJHH7yrNaLf8itvyq6QA4wiIjLGgXFj/YzooOu6PgQoRM6AHTzjixPi5JI0AVWWaEhBEKsgk4+BdNT1djdszY/dbmPSCNhLymzQtWyl7SMrBZjQ4LJSkQsUAEBjCB93SPcEhk1TwSybjW/3IrhJVgS3Zzi/zaQQaHJOj9nvoAhhfkpmyHzPDC8VwGK7B6dty5EMLs+jyEu+XbsfdM2v8j1OpZwD6NzGyzvvAUcoXi4kZaJJXPAglel2L2Q3y8Nepydh8RLY0/7USI9JCp0W9dZFmhKskdxoLN8kZIQpili0h5jlzKs+ulZxmtVUEjuS/OuA==
    password: AgBWtb90ZNrFRujIx06vi7621T0tGX/tdFOd7lwxtArX9ySao5l51l/RxCg3QL4Hw/EoqZg9yUkCBVPiFUuOYUvW4UIVTcdqTWBscDv9f8OP5dUx1O6SgXBK/Z0Ak3fz9x14kIGkBHDzfYMWyb8g6izM2mlypVOkE5m01YEezI3+tsPYSSXl7jzfpISEHZTfQP5ul8VjtyywUcAFpRpYGkL0+I4OZXuib/y0BgIh9OLhE0XyMRYTe2cagcQkr885dLjMtv95IzXe2D6+vkSCRz9pw0cZmr+w7sJSUmw1LeE6dYwZZofPevKhwiZ1bL1tqHwGyHELCTSxA/XanJRa5OsLgXm3tQNceGEEMPd+tMgdDLFKbg7H9Sgliwvo3OejasdWFqVv3SF2cqwYAnzwQ19PwniTnAbcxg4sl24mNMYb1TfBkbYn+Gv6FVnXaVapC8IMzBJVI58nJ6aP9btY6ASSjv6sNmajt0KnhzFGFbjQWx2D3C2+rNGk4lRG+sWj8He13XS16lxuiomTLm6gVvpJPZqlvxlORFmkSDaqoyEP9j3R1NfBRoJwATaPIEPNaFC5F4lLHL80IiWx+ORCuQ4VVbT4+0tOd+PJtbukd7ieF6PbjDBfS3kxtTHPh0eEtbVEnuS1142FwopS9abqq7Z15iYz2QoF6p8PgM3/oS7LaePbVq7iltffCQ5c8Jz7Fxc=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: grafana
