apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
spec:
  subscriptions:
    warehouse: homelab-platform-sources
  promotionMechanisms:
    gitRepoUpdates:
    - helm:
        charts:
          - chartPath: k8s/helm/argocd/argocd
            name: argo-cd
            registryURL: https://argoproj.github.io/argo-helm
      readBranch: main
      repoURL: https://github.com/zbialik/gitops.git
      writeBranch: main
    - helm:
        charts:
          - chartPath: k8s/helm/cert-manager/cert-manager
            name: cert-manager
            registryURL: https://charts.jetstack.io
      readBranch: main
      repoURL: https://github.com/zbialik/gitops.git
      writeBranch: main
    - helm:
        charts:
          - chartPath: k8s/helm/grafana/grafana
            name: grafana
            registryURL: https://grafana.github.io/helm-charts
      readBranch: main
      repoURL: https://github.com/zbialik/gitops.git
      writeBranch: main
    - helm:
        charts:
          - chartPath: k8s/helm/ingress-nginx/ingress-nginx
            name: ingress-nginx
            registryURL: https://kubernetes.github.io/ingress-nginx
      readBranch: main
      repoURL: https://github.com/zbialik/gitops.git
      writeBranch: main
    - helm:
        charts:
          - chartPath: k8s/helm/longhorn-system/longhorn
            name: longhorn
            registryURL: https://charts.longhorn.io
      readBranch: main
      repoURL: https://github.com/zbialik/gitops.git
      writeBranch: main
    - helm:
        charts:
          - chartPath: k8s/helm/metallb-system/metallb
            name: metallb
            registryURL: https://metallb.github.io/metallb
      readBranch: main
      repoURL: https://github.com/zbialik/gitops.git
      writeBranch: main
    - helm:
        charts:
          - chartPath: k8s/helm/monitoring/node-exporter
            name: prometheus-node-exporter
            registryURL: https://prometheus-community.github.io/helm-charts
      readBranch: main
      repoURL: https://github.com/zbialik/gitops.git
      writeBranch: main
    - helm:
        charts:
          - chartPath: k8s/helm/monitoring/prometheus-adapter
            name: prometheus-adapter
            registryURL: https://prometheus-community.github.io/helm-charts
      readBranch: main
      repoURL: https://github.com/zbialik/gitops.git
      writeBranch: main
    - helm:
        charts:
          - chartPath: k8s/helm/kube-system/sealed-secrets-controller
            name: sealed-secrets
            registryURL: https://bitnami-labs.github.io/sealed-secrets
      readBranch: main
      repoURL: https://github.com/zbialik/gitops.git
      writeBranch: main
    - helm:
        charts:
          - chartPath: k8s/helm/test/test-kargo-promotion
            name: test-kargo-promotion
            registryURL: https://zbialik.github.io/helm-charts
      readBranch: main
      repoURL: https://github.com/zbialik/gitops.git
      writeBranch: main
    argoCDAppUpdates:
    - appName: argocd
      appNamespace: argocd
    - appName: cert-manager
      appNamespace: argocd
    - appName: grafana
      appNamespace: argocd
    - appName: ingress-nginx
      appNamespace: argocd
    - appName: longhorn
      appNamespace: argocd
    - appName: metallb
      appNamespace: argocd
    - appName: node-exporter
      appNamespace: argocd
    - appName: prometheus-adapter
      appNamespace: argocd
    - appName: sealed-secrets-controller
      appNamespace: argocd
    - appName: test-kargo-promotion
      appNamespace: argocd
