apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: homelab-platform-sources
spec:
  subscriptions:
  - chart:
      name: argo-cd
      registryURL: https://argoproj.github.io/argo-helm
      semverConstraint: ^5.51.6
  - chart:
      name: cert-manager
      registryURL: https://charts.jetstack.io
      semverConstraint: ^v1.13.3
  - chart:
      name: grafana
      registryURL: https://grafana.github.io/helm-charts
      semverConstraint: ^7.0.0
  - chart:
      name: ingress-nginx
      registryURL: https://kubernetes.github.io/ingress-nginx
      semverConstraint: ^4.8.0
  - chart:
      name: longhorn
      registryURL: https://charts.longhorn.io
      semverConstraint: ^1.5.3
  - chart:
      name: metallb
      registryURL: https://metallb.github.io/metallb
      semverConstraint: ^0.13.12
  - chart:
      name: prometheus-node-exporter
      registryURL: https://prometheus-community.github.io/helm-charts
      semverConstraint: ^4.21.0
  - chart:
      name: prometheus-adapter
      registryURL: https://prometheus-community.github.io/helm-charts
      semverConstraint: ^4.0.0
  - chart:
      name: sealed-secrets
      registryURL: https://bitnami-labs.github.io/sealed-secrets
      semverConstraint: ^2.13.3
  - chart:
      name: test-kargo-promotion
      registryURL: https://zbialik.github.io/helm-charts
      semverConstraint: ^1.0.0
