
auth:
  createDatabase: true
  database: "jhu"
  username: "zbialik"
  existingSecret: mysql # contains root + zbialik passwords

primary:
  persistence:
    existingClaim: "mysql-hostpath"
  podSecurityContext:
    enabled: true
    fsGroup: 1000
    fsGroupChangePolicy: "Always"
  containerSecurityContext:
    runAsUser: 1000

  service:
    type: LoadBalancer
