
auth:
  createDatabase: true
  database: "jhu"
  username: "zbialik"
  existingSecret: mysql # contains root + zbialik passwords

primary:
  persistence:
    existingClaim: "mysql-hostpath"
  podSecurityContext:
    enabled: true
    fsGroup: 1001
    fsGroupChangePolicy: "Always"


  service:
    type: LoadBalancer
