
auth:
  createDatabase: true
  database: "jhu"
  username: "zbialik"
  existingSecret: mysql # contains root + zbialik passwords

primary:
  persistence:
    existingClaim: "mysql-hostpath"
  podSecurityContext:
    enabled: true
    fsGroup: 1000
    fsGroupChangePolicy: "Always"
  containerSecurityContext:
    runAsUser: 1000

  service:
    nodePorts:
      mysql: "31201"
    annotations:
      metallb.universe.tf/allow-shared-ip: "homelab-192.168.0.181"
    loadBalancerIP: 192.168.0.181
    type: LoadBalancer
