apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/zbialik/gitops.git
      revision: homelab
      directories:
      - path: "*"
  template:
    metadata:
      name: '{{path[0]}}'
      annotations:
        # must match kargo-appset destination.namespace + stage defined in manifests
        kargo.akuity.io/authorized-stage: "kargo-{{path[0]}}:dev"
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
      source:
        repoURL: https://github.com/zbialik/gitops.git
        targetRevision: homelab
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'default' # should be overridden in generated.yaml
