apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/zbialik/homelab.git
      revision: main
      directories:
      - path: k8s/*/*/*/kargo
  template:
    metadata:
      name: 'kargo-{{path[3]}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
        syncOptions:
        - Replace=true
      source:
        repoURL: https://github.com/zbialik/homelab.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'kargo-homelab'
