apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/zbialik/homelab.git
      revision: main
      directories:
      - path: k8s/kargo-manifests/*
      - path: k8s/kargo-manifests/base
        exclude: true
  template:
    metadata:
      name: 'kargo-{{path[2]}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
        syncOptions:
        - Replace=true
        - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            kargo.akuity.io/project: "true" # apply kargo project label to created namespace
      source:
        repoURL: https://github.com/zbialik/homelab.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'kargo-{{path[2]}}' # represents kargo project
