apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-hostpath
spec:
  capacity: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/usb01/k8s/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-hostpath
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: mysql-hostpath # Use the name of your PersistentVolume (PV) if one exists
  selector:
    matchLabels:
      app: mysql # Match labels with your MySQL pod
