kind: Kustomization
namespace: argocd
commonLabels:
  app: argocd

resources:
- namespace.yaml
- generated.yaml
- sealed-secret.yaml

patches:
- target:
    kind: Service
    name: argocd-server
  patch: |-
    - op: replace
      path: /spec/type
      value: NodePort
