apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: prometheus-node-exporter
  namespace: kargo-homelab
spec:
  subscriptions:
  - chart:
      name: prometheus-node-exporter
      registryURL: https://prometheus-community.github.io/helm-charts
      semverConstraint: ^4.23.0
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prometheus-node-exporter-dev
  namespace: kargo-homelab
spec:
  subscriptions:
    warehouse: prometheus-node-exporter
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/zbialik/homelab.git
      writeBranch: main
      helm:
        charts:
        - chartPath: k8s/helm/monitoring/node-exporter
          name: prometheus-node-exporter
          registryURL: https://prometheus-community.github.io/helm-charts
    argoCDAppUpdates:
    - appName: node-exporter
      appNamespace: argocd
