apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: node-exporter
  namespace: kargo-homelab
spec:
  subscriptions:
  - chart:
      name: prometheus-node-exporter
      registryURL: https://prometheus-community.github.io/helm-charts
      semverConstraint: ^4.21.0
