apiVersion: 1
datasources:
- name: prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus.monitoring.svc.cluster.local.:9090
  version: 1
  isDefault: true
  editable: false
