kind: Kustomization
namespace: grafana
commonLabels:
  app.kubernetes.io/name: grafana
  app.zb/name: grafana

resources:
- sealed-secret.yaml
# - generated.yaml

configMapGenerator:
- name: grafana-provisioning-datasources
  options:
    labels:
      grafana.zb/datasource: ""
  files:
  - files/datasources.yaml
