---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    password: AgB8XsPWXlPMJ5gfIYUoNL4kbXGNmliV9EL6zScXZnhQWz806sOW1jC+7fLkvyOOkIT2OHev7xkpfziOQCQhoe/c+2dT4FOsOFmhD9YcabIaTNUMGdy+7pNUBlS3mtiJ3vmN8hgrX6hH6babWswxfyQ+dioMOK2oc4mFJIx6ZArAY/TE52RIsABC3JkFRVwhjBzfhtiM7SZwe8Pzibe4JjTP7wKoxBQhnVf7+MMt36y7jtSDaZtKn9llTi4x3wxcDsabUk7pKCK9GRnni0PnonJ9Xi9C7w0xfBEbmlXFKOsIF2vuDo7wY7ce71a1EOvqPSsCqyNMm0DK6IhmfOoexyoY+LlsqnAQ9QeES3iyqAWjcajM9ZVZszeyrxSUSlHMHKhbknmmiFuMgBy1bEzqU7L5lD8WJS2IEDzAPmSts29NWpHFdAJ3W15RF7CUVdwjd4uHzUuWL1sa4gInJlAlA5aJj7CekUnMW1/JXPyQREuBGeXsgamCrykn6vJYmFe1oadqZ/z1jrhPV/HXaFE5+ZYmM+U0rfAtuZTD+muM02zNxN3ZmmW8RzkVf3iG0N+IZbeWCCluJlCTKwrKITLYUvxVc8fi5pW6DEcRtIEqOG8wSjdfj2IC+0JkQhZoc+Wdid0rTJtv4fZQC8AFzgf+1bCpsflza1MxnsWDbiazQK7se8rjvIELKTCcNDYZIDTGO48zFEllzVCLmWwTLUEbGZ4DIQJjdussKcek+d850HSzn1+PJrz+2KXZjxwLimg0OL653ZqHx71TlByelwU=
    username: AgBSJklhYZGpsV1GnxXx3FYeLytMr/M/odgAZoy0HLv576k99VGDN76er7IKsOBZzDdDAkCXhwoqne8EhIIVQVCOVjD45FaTJNGtUV/l+iUC7L2aJ3mWW29rSqjtaUtEfVOkpngZM6EVnZOnWeOiDBeDgaNwE6lE22e0uBGn1yVxdGAgWp3F6EQUoDdlCLv1mHO9bTcoC3exjzNV6xINvcIXe2HYX/61vmS8aiXOrDizsayuoAQJwLnhP1dDw7eLfFvORqPY6bfQId03DTUyLOzaPZFTWrQ48ICCriIGbYr4qtBxQM6wkaXvbZhUqnAd96C604bBtov0ZSRT6Uh81L/8lEohAMS/ojHyJEdZChFI42oTIenmyXac6WBZxLrorRTT+ejEvarnbjp5D0x666M6o+Lt5QQHrUXDED31ivcXProNO1gksZY2yGTEsfM5ZQqoNiwZda3q8IVST0TSNhgsecMQ6Mx6PQ2sjs2uth8VkNBVFrn7ZNNXcbGg5HSeiPW759pSubXe8FY4qHr/vd58+6pdccXtSVJcgyy3F94124aVWy881kFUDzduA8GdQy4Tbxf5tAWTuCz8JKdmeNasYFKEwqZ2qlM5Z3UZC8Sr3wUD+UH4L6MgyNnqVjB2ektY3ecuoDPyM3SbsSWs30sGlXa3vfzaUWjWO7JqyVGiXMdA0384hbtWbUr52M/8BvKJsUvG4Q==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: grafana
