apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: systemd-exporter
  labels:
    name: systemd-exporter
    app.kubernetes.io/name: systemd-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: systemd-exporter
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: systemd-exporter
    spec:
      securityContext:
        runAsUser: 0
      hostPID: true
      containers:
      - name: systemd-exporter
        image: quay.io/prometheuscommunity/systemd-exporter:v0.6.0
        securityContext:
          privileged: true
        args:
        - --log.level=info
        - --systemd.collector.unit-include=containerd.service|kubelet.service
        ports:
        - name: metrics
          containerPort: 9558
          hostPort: 9558
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: systemd
          mountPath: /run/systemd
          readOnly: true
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 100Mi
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: systemd
        hostPath:
          path: /run/systemd
