apiVersion: v1
kind: Service
metadata:
  name: systemd-exporter
  labels:
    app.kubernetes.io/name: systemd-exporter
spec:
  type: ClusterIP
  ports:
    - port: 9558
      targetPort: 9558
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: systemd-exporter
