kind: Kustomization
resources: 
- ../base
- sealed-secret.yaml

patches:
- target:
    group: kargo.akuity.io
    version: v1alpha1
    kind: Stage
  patch: |-
    - op: add
      path: /spec/promotionMechanisms/argoCDAppUpdates/0/appName
      value: argocd
    - op: add
      path: /spec/promotionMechanisms/gitRepoUpdates/0/helm
      value:
        charts:
        - chartPath: k8s/helm/argocd/argocd
          name: argo-cd
          registryURL: https://argoproj.github.io/argo-helm
- target:
    group: kargo.akuity.io
    version: v1alpha1
    kind: Warehouse
  patch: |-
    - op: add
      path: /spec/subscriptions
      value:
      - chart:
          name: argo-cd
          registryURL: "https://argoproj.github.io/argo-helm"
          semverConstraint: ^5.51.6 # most-recent stable 5.x.x version (but less than 6.0.0) 
