{
 "title": "Kubernetes Pods/Containers Resources",
 "description": "Display usage of resources by pod or container in kubernetes cluster.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "label": "Cluster", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"},container)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_node_info,node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node Allocatable Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "$node allocatable",
     "type": "stat",
     "description": "allocatable cpu and memory resources for $node",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
     "repeat": "node",
     "fieldConfig": { "defaults": { "unit": "cores" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(kube_node_status_allocatable{resource=\"cpu\",node=\"$node\"})",
       "legendFormat": "Allocatable CPU"
      },
      {
       "expr": "max(kube_node_status_allocatable{resource=\"memory\",node=\"$node\"})",
       "legendFormat": "Allocatable Memory"
      }
     ]
    }
   ]
  },
  { "title": "Node Remaining Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "$node remaining",
   "type": "stat",
   "description": "remaining cpu and memory resources for $node",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 2 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_node_status_allocatable{resource=\"cpu\",node=\"$node\"}) - sum(max(kube_pod_container_resource_requests{resource=\"cpu\",node=\"$node\"}) by (namespace,pod,container))",
     "legendFormat": "Remaining CPU"
    },
    {
     "expr": "max(kube_node_status_allocatable{resource=\"memory\",node=\"$node\"}) - sum(max(kube_pod_container_resource_requests{resource=\"memory\",node=\"$node\"}) by (namespace,pod,container))",
     "legendFormat": "Remaining Memory"
    }
   ]
  },
  {
   "title": "$node % allocated",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(kube_pod_container_resource_requests{resource=\"cpu\",node=\"$node\"}) by (namespace,pod,container)) / max(kube_node_status_allocatable{resource=\"cpu\",node=\"$node\"})",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum(max(kube_pod_container_resource_requests{resource=\"memory\",node=\"$node\"}) by (namespace,pod,container)) / max(kube_node_status_allocatable{resource=\"memory\",node=\"$node\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "millcore" } },
   "targets": [
    {
     "expr": "sum by(namespace,pod,container) (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",node=~\"$node\"}[$__rate_interval])) * 1000",
     "legendFormat": "{{pod}} | {{container}}"
    }
   ]
  },
  {
   "title": "CPU % of Limits",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(namespace,pod,container) (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",node=~\"$node\"}[$__rate_interval])) / on(namespace,pod,container) kube_pod_container_resource_limits{resource=\"cpu\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",node=~\"$node\"}",
     "legendFormat": "{{pod}} | {{container}}"
    }
   ]
  },
  {
   "title": "CPU % of Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(namespace,pod,container) (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",node=~\"$node\"}[$__rate_interval])) / on(namespace,pod,container) kube_pod_container_resource_requests{resource=\"cpu\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",node=~\"$node\"}",
     "legendFormat": "{{pod}} | {{container}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod,container) (container_memory_usage_bytes{pod=~\"$pod\", container=~\"$container\", container!=\"POD\"})",
     "legendFormat": "{{pod}} | {{container}}"
    }
   ]
  },
  {
   "title": "Memory % of Limits",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(namespace,pod,container) (container_memory_usage_bytes{pod=~\"$pod\", container=~\"$container\", container!=\"POD\"})/ on(namespace,pod,container) kube_pod_container_resource_limits{resource=\"memory\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",node=~\"$node\"}",
     "legendFormat": "{{pod}} | {{container}}"
    }
   ]
  },
  {
   "title": "Memory % of Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(namespace,pod,container) (container_memory_usage_bytes{pod=~\"$pod\", container=~\"$container\", container!=\"POD\"})/ on(namespace,pod,container) kube_pod_container_resource_requests{resource=\"memory\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",node=~\"$node\"}",
     "legendFormat": "{{pod}} | {{container}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Network RX",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sort_desc(sum by (pod) (rate (container_network_receive_bytes_total{pod=~\"$pod\"}[1m]) ))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network TX",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sort_desc(sum by (pod) (rate (container_network_transmit_bytes_total{pod=~\"$pod\"}[1m]) ))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}